test:
  name: hutao

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: 218549442
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**